source/Ellucian.Colleague.Api/Ellucian.Colleague.Api/Controllers/UtilitiesController.cs
// Copyright 2013-2014 Ellucian Company L.P. and its affiliates.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using Ellucian.Web.Mvc.Filter;
using System.Runtime.Caching;
using System.Collections;
using Ellucian.Web.Cache;

namespace Ellucian.Colleague.Api.Controllers
{
    /// <summary>
    /// Provides a top-level controller for API utilities.
    /// </summary>
    [LocalRequest]
    public class UtilitiesController : Controller
    {
        /// <summary>
        /// Gets the index page.
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Gets the clear cache page. This action currently clears the cache.
        /// </summary>
        /// <returns></returns>
        public ActionResult ClearCache()
        {
            var cacheProvider = DependencyResolver.Current.GetService<ICacheProvider>();
            List<string> filter = new List<string> { "Repositories" };

            UtilityCacheRepository cacheRepo = new UtilityCacheRepository(cacheProvider);
            cacheRepo.ClearCache(filter);

            return View();
        }

        /// <summary>
        /// Private repository class which extends the base caching repository; a bit of a hack so this controller
        /// can access methods in the abstract base caching repository
        /// </summary>
        private class UtilityCacheRepository : BaseCachingRepository
        {
            protected internal UtilityCacheRepository(ICacheProvider cacheProvider)
                : base(cacheProvider)
            {
            }
        }
    }
}

source/Ellucian.Colleague.Api/Ellucian.Colleague.Api/Views/Utilities/ClearCache.cshtml
@{
    ViewBag.Title = "Clear Cache";
}

@* Header/Title *@
<div class="esg-page-header">
    <h2 class="esg-page-header__title header-margin">@ViewBag.Title</h2>
</div>

<div id="ClearCachebody" class="base">
    <section class="content-wrapper main-content clear-fix">
        <br/><h3>Repository data caches cleared successfully</h3><br/>
    </section>
</div>

source/Ellucian.Colleague.Api/Ellucian.Colleague.Api/Views/Utilities/Index.cshtml
@{
    ViewBag.Title = "Colleague Web API Utilities";
}

@* Header/Title *@
<div class="esg-page-header">
    <h2 class="esg-page-header__title header-margin">@ViewBag.Title</h2>
</div>
@* FieldSet *@
<div id="Utilitiesbody">
    <section class="content-wrapper main-content clear-fix">
        <br />
        <h3 class="base">Module Utilities</h3>
        <table class="APISettingstable">
            @if (System.IO.File.Exists(Server.MapPath(@"~\Areas\Student\Views\Test\Index.cshtml")))
            {
                <tr>
                    <td>@Html.ActionLink("Student Utility Tests", "", "Student/Test", null, null)</td>
                </tr>
            }
            @if (System.IO.File.Exists(Server.MapPath(@"~\Areas\Planning\Views\Test\Index.cshtml")))
            {
                <tr>
                    <td>@Html.ActionLink("Planning Utility Tests", "", "Planning/Test", null, null)</td>
                </tr>
            }
        </table>

        <h3 class="base">Global Utilities</h3>
        <table class="APISettingstable">
            <tr>
                <td>@Html.ActionLink("Clear Data Caches", "ClearCache", "Utilities", null, null) without recycling the application pool.</td>
            </tr>
        </table>

    </section>
</div>