source/Ellucian.Colleague.Api/Ellucian.Colleague.Api/Areas/Planning/Models/Tests/TestEvaluation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Ellucian.Colleague.Api.Areas.Planning.Models.Tests
{
    /// <summary>
    /// Test evaluation model
    /// </summary>
    public class TestEvaluation
    {
        /// <summary>
        /// Gets or sets the program.
        /// </summary>
        public string Program { get; set; }
    }
}

source/Ellucian.Colleague.Api/Ellucian.Colleague.Api/Areas/Planning/Models/Tests/TestEvaluationResult.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Ellucian.Colleague.Api.Areas.Planning.Models.Tests
{
    /// <summary>
    /// Test evaluation result model.
    /// </summary>
    public class TestEvaluationResult
    {
        /// <summary>
        /// Gets or sets the person id.
        /// </summary>
        public string PersonId { get; set; }

        /// <summary>
        /// Gets or sets the program id.
        /// </summary>
        public string ProgramId { get; set; }

        /// <summary>
        /// Gets or sets the evaluation result text.
        /// </summary>
        public string Evaluation { get; set; }

        /// <summary>
        /// Gets or sets the evaluation log.
        /// </summary>
        public string Log { get; set; }
    }
}

source/Ellucian.Colleague.Api/Ellucian.Colleague.Api/Areas/Planning/Controllers/TestController.cs
// Copyright 2012-2013 Ellucian Company L.P. and its affiliates.
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using Ellucian.Colleague.Api.Areas.Planning.Models.Tests;
using Ellucian.Colleague.Api.Client;
using Ellucian.Colleague.Api.Models;
using Microsoft.IdentityModel.Claims;
using slf4net;
using System.Net;
using Ellucian.Web.Mvc.Filter;
using Ellucian.Web.Http.Configuration;
using Ellucian.Web.Security;
using Ellucian.Logging;

namespace Ellucian.Colleague.Api.Areas.Planning.Controllers
{
    /// <summary>
    /// Provides the test utilities for the planning area.
    /// </summary>
    [LocalRequest]
    public class TestController : Controller
    {
        /// <summary>
        /// Person id string.
        /// </summary>
        public static string PersonIdKey = "PersonId";

        private StringLogger logger = new StringLogger();

        /// <summary>
        /// Gets the test index page.
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            var tests = new ApiTests();
            tests.Tests.Add("subjects");
            return View(tests);
        }

        /// <summary>
        /// Gets the test degree plan index page.
        /// </summary>
        /// <returns></returns>
        public ActionResult DegreePlan()
        {
            return View();
        }

        /// <summary>
        /// Submits a request to run the degree plan test.
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult PostDegreePlan()
        {
            var sw = new Stopwatch();
            sw.Start();
            var results = CreateClient().GetOrCreateDegreePlanForStudent((string)HttpContext.Items[PersonIdKey]);
            sw.Stop();
            TempData["elapsed"] = sw.ElapsedMilliseconds;
            return RedirectToAction("Done");
        }

        /// <summary>
        /// Gets the test advisees index page.
        /// </summary>
        /// <returns></returns>
        public ActionResult Advisees()
        {
            return View();
        }

        /// <summary>
        /// Submits a request to run the advisees test.
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult PostAdvisees()
        {
            var sw = new Stopwatch();
            sw.Start();
            var results = CreateClient().GetAdvisor((string)HttpContext.Items[PersonIdKey]);
            sw.Stop();
            TempData["elapsed"] = sw.ElapsedMilliseconds;
            return RedirectToAction("Done");
        }

        /// <summary>
        /// Gets the test evaluation page.
        /// </summary>
        /// <returns></returns>
        public ActionResult Evaluation()
        {
            return View();
        }

        /// <summary>
        /// Submits a request to run the evaluation test.
        /// </summary>
        /// <param name="evaluation"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Evaluation(TestEvaluation evaluation)
        {
            return Run(() =>
            {
                var result = CreateClient().GetProgramEvaluation((string)HttpContext.Items[PersonIdKey], evaluation.Program);
                return result.RequirementResults.Count + " requirement results";
            });
        }

        /// <summary>
        /// Gets the done page.
        /// </summary>
        /// <returns></returns>
        public ActionResult Done()
        {
            ViewBag.Result = TempData["result"];
            ViewBag.Elapsed = (long)TempData["elapsed"];
            var ex = (Exception) TempData["exception"];
            if (ex != null) 
            {
                ViewBag.ExceptionMessage = ex.ToString();
                ViewBag.Log = (string)TempData["log"];
            }
            return View();
        }


        private ColleagueApiClient CreateClient()
        {
            var cookie = LocalUserUtilities.GetCookie(Request);
            var cookieValue = cookie == null ? null : cookie.Value;
            if (string.IsNullOrEmpty(cookieValue))
            {
                throw new Exception("Log in first");
            }
            var baseUrl = cookieValue.Split('*')[0];
            var token = cookieValue.Split('*')[1];
            var principal = JwtHelper.CreatePrincipal(token);
            var personId = (principal as IClaimsPrincipal).Identities.First().Claims.First(claim => claim.ClaimType == ClaimConstants.PersonId).Value;
            HttpContext.Items[PersonIdKey] = personId;
            var client = new ColleagueApiClient(baseUrl, logger);
            client.Credentials = token;
            return client;
        }

        private static List<string> GetDelimited(string input)
        {
            if (input == null)
            {
                return new List<string>();
            }
            if (input.Contains(','))
            {
                return input.Split(',').Where(s => !string.IsNullOrEmpty(s)).ToList();
            }
            return input.Split(' ').Where(s => !string.IsNullOrEmpty(s)).ToList();
        }

        private ActionResult Run(Func<string> action) {
            var sw = new Stopwatch();
            logger.Clear();
            sw.Start();
            string result = "";
            try
            {
                result = action.Invoke();
            }
            catch (Exception ex)
            {
                TempData["exception"] = ex;
            }
            sw.Stop();
            TempData["result"] = result;
            TempData["elapsed"] = sw.ElapsedMilliseconds;
            TempData["log"] = logger.ToString();
            logger.Clear();
            return RedirectToAction("Done");
        }
    }
}

source/Ellucian.Colleague.Api/Ellucian.Colleague.Api/Controllers/Student/SectionsController.cs
// Copyright 2014-2017 Ellucian Company L.P. and its affiliates.

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Net;
using System.Runtime.Serialization;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web.Http;
using Ellucian.Colleague.Api.Licensing;
using Ellucian.Colleague.Api.Utility;
using Ellucian.Colleague.Configuration.Licensing;
using Ellucian.Colleague.Coordination.Student.Services;
using Ellucian.Colleague.Domain.Base.Exceptions;
using Ellucian.Colleague.Domain.Exceptions;
using Ellucian.Colleague.Domain.Student.Repositories;
using Ellucian.Colleague.Dtos;
using Ellucian.Colleague.Dtos.EnumProperties;
using Ellucian.Colleague.Dtos.Student;
using Ellucian.Web.Adapters;
using Ellucian.Web.Http.Controllers;
using Ellucian.Web.Http.Exceptions;
using Ellucian.Web.Http.Filters;
using Ellucian.Web.License;
using Ellucian.Web.Security;
using slf4net;
using Ellucian.Web.Http;
using Ellucian.Web.Http.Models;
using Newtonsoft.Json;
using Section = Ellucian.Colleague.Dtos.Student.Section;
using Section2 = Ellucian.Colleague.Dtos.Student.Section2;
using Section3 = Ellucian.Colleague.Dtos.Student.Section3;

namespace Ellucian.Colleague.Api.Controllers.Student
{
    /// <summary>
    /// Provides access to course Section data.
    /// </summary>
    [Authorize]
    [LicenseProvider(typeof (EllucianLicenseProvider))]
    [EllucianLicenseModule(ModuleConstants.Student)]
    public class SectionsController : BaseCompressedApiController
    {
        private readonly ISectionCoordinationService _sectionCoordinationService;
        private readonly ISectionRegistrationService _sectionRegistrationService;
        private readonly IRegistrationGroupService _registrationGroupService;
        private readonly ISectionRepository _sectionRepository;
        private readonly IAdapterRegistry _adapterRegistry;
        private readonly ILogger _logger;

        /// <summary>
        /// Initializes a new instance of the SectionsController class.
        /// </summary>
        /// <param name="adapterRegistry">Adapter registry of type <see cref="IAdapterRegistry">IAdapterRegistry</see></param>
        /// <param name="sectionRepository">Repository of type <see cref="ISectionRepository">ISectionRepository</see></param>
        /// <param name="sectionCoordinationService">Service of type <see cref="ISectionCoordinationService">ISectionCoordinationService</see></param>
        /// <param name="sectionRegistrationService">Service of type <see cref="ISectionRegistrationService">ISectionRegistrationService</see></param>
        /// <param name="registrationGroupService">Service of type <see cref="IRegistrationGroupService">IRegistrationGroupService</see></param>
        /// <param name="logger">Logger of type <see cref="ILogger">ILogger</see></param>
        public SectionsController(IAdapterRegistry adapterRegistry,
            ISectionRepository sectionRepository,
            ISectionCoordinationService sectionCoordinationService,
            ISectionRegistrationService sectionRegistrationService,
            IRegistrationGroupService registrationGroupService,
            ILogger logger)
        {
            _adapterRegistry = adapterRegistry;
            _sectionRepository = sectionRepository;
            _sectionCoordinationService = sectionCoordinationService;
            _sectionRegistrationService = sectionRegistrationService;
            _registrationGroupService = registrationGroupService;
            _logger = logger;
        }

        /// <summary>
        /// Retrieves information about a specific course section. 
        /// If the request header "Cache-Control" attribute is set to "no-cache" the data returned will be pulled fresh from the database, otherwise cached data is returned.
        /// </summary>
        /// <param name="sectionId">Id of the section desired</param>
        /// <returns>The requested <see cref="Dtos.Student.Section">Section</see></returns>
        ///[CacheControlFilter(Public = true, MaxAgeHours = 1, Revalidate = true)]
        [Obsolete("Obsolete as of Api version 1.3, use version 2 of this API")]
        [ParameterSubstitutionFilter]
        public async Task<Section> GetSectionAsync(string sectionId)
        {
            IEnumerable<string> listOfIds = new List<string>() {sectionId};
            IEnumerable<Ellucian.Colleague.Domain.Student.Entities.Section> sectionEntities = new List<Ellucian.Colleague.Domain.Student.Entities.Section>();
            bool useCache = true;
            if (Request.Headers.CacheControl != null)
            {
                if (Request.Headers.CacheControl.NoCache)
                {
                    useCache = false;
                }
            }
            if (useCache)
            {
                sectionEntities = await _sectionRepository.GetCachedSectionsAsync(listOfIds);
            }
            else
            {
                sectionEntities = await _sectionRepository.GetNonCachedSectionsAsync(listOfIds);
            }
            Ellucian.Colleague.Domain.Student.Entities.Section sectionEntity = sectionEntities.Where(s => s.Id == sectionId).FirstOrDefault();
            if (sectionEntity == null)
            {
                throw CreateNotFoundException("section", sectionId);
            }
            // Get the right adapter for the type mapping
            var sectionDtoAdapter = _adapterRegistry.GetAdapter<Ellucian.Colleague.Domain.Student.Entities.Section, Section>();

            // Map the section entity to the section Dto then set up response and cache for the single item.
            Section sectionDto = sectionDtoAdapter.MapToType(sectionEntity);

            return sectionDto;
        }

        /// <summary>
        /// Retrieves information about a specific course section. 
        /// If the request header "Cache-Control" attribute is set to "no-cache" the data returned will be pulled fresh from the database, otherwise cached data is returned.
        /// </summary>
        /// <param name="sectionId">Id of the section desired</param>
        /// <returns>The requested <see cref="Dtos.Student.Section2">Section</see></returns>
        ///[CacheControlFilter(Public = true, MaxAgeHours = 1, Revalidate = true)]
        [Obsolete("Obsolete as of Api version 1.5, use version 3 of this API")]
        [ParameterSubstitutionFilter]
        public async Task<Section2> GetSection2Async(string sectionId)
        {
            IEnumerable<string> listOfIds = new List<string>() {sectionId};
            IEnumerable<Ellucian.Colleague.Domain.Student.Entities.Section> sectionEntities = new List<Ellucian.Colleague.Domain.Student.Entities.Section>();
            bool useCache = true;
            if (Request.Headers.CacheControl != null)
            {
                if (Request.Headers.CacheControl.NoCache)
                {
                    useCache = false;
                }
            }
            if (useCache)
            {
                sectionEntities = await _sectionRepository.GetCachedSectionsAsync(listOfIds);
            }
            else
            {
                sectionEntities = await _sectionRepository.GetNonCachedSectionsAsync(listOfIds);
            }
            Ellucian.Colleague.Domain.Student.Entities.Section sectionEntity = sectionEntities.Where(s => s.Id == sectionId).FirstOrDefault();
            if (sectionEntity == null)
            {
                throw CreateNotFoundException("section", sectionId);
            }
            // Get the right adapter for the type mapping
            var sectionDtoAdapter = _adapterRegistry.GetAdapter<Ellucian.Colleague.Domain.Student.Entities.Section, Section2>();

            // Map the section entity to the section Dto then set up response and cache for the single item.
            Section2 sectionDto = sectionDtoAdapter.MapToType(sectionEntity);

            return sectionDto;
        }


        /// <summary>
        /// Retrieves information about a specific course section. 
        /// If the request header "Cache-Control" attribute is set to "no-cache" the data returned will be pulled fresh from the database, otherwise cached data is returned.
        /// </summary>
        /// <param name="sectionId">Id of the section desired</param>
        /// <returns>The requested <see cref="Dtos.Student.Section3">Section3</see></returns>
        [ParameterSubstitutionFilter]
        public async Task<Section3> GetSection3Async(string sectionId)
        {
            IEnumerable<string> listOfIds = new List<string>() {sectionId};
            IEnumerable<Ellucian.Colleague.Domain.Student.Entities.Section> sectionEntities = new List<Ellucian.Colleague.Domain.Student.Entities.Section>();
            bool useCache = true;
            if (Request.Headers.CacheControl != null)
            {
                if (Request.Headers.CacheControl.NoCache)
                {
                    useCache = false;
                }
            }
            if (useCache)
            {
                sectionEntities = await _sectionRepository.GetCachedSectionsAsync(listOfIds);
            }
            else
            {
                sectionEntities = await _sectionRepository.GetNonCachedSectionsAsync(listOfIds);
            }
            Ellucian.Colleague.Domain.Student.Entities.Section sectionEntity = sectionEntities.Where(s => s.Id == sectionId).FirstOrDefault();
            if (sectionEntity == null)
            {
                throw CreateNotFoundException("section", sectionId);
            }
            // Get the right adapter for the type mapping
            var sectionDtoAdapter = _adapterRegistry.GetAdapter<Ellucian.Colleague.Domain.Student.Entities.Section, Section3>();

            // Map the section entity to the section Dto then set up response and cache for the single item.
            Section3 sectionDto = sectionDtoAdapter.MapToType(sectionEntity);

            return sectionDto;

source/Ellucian.Colleague.Api/Ellucian.Colleague.Api/Areas/Student/Views/Test/CourseSearch.cshtml
@model Ellucian.Colleague.Api.Areas.Student.Models.Tests.TestCourseSearch

@{
    ViewBag.Title = "CourseSearch";
}
@* Header/Title *@
<div class="esg-page-header">
    <h2 class="esg-page-header__title header-margin">Course Search</h2>
    <a href="@Url.Action("", "Test")" class="esg-page-header__subtitle esg-page-header__subtitle--backlink">
        <span class="esg-icon__container esg-page-header__icon" aria-hidden="true">
            <svg class="esg-icon esg-icon--left">
                <use xlink:href="#icon-arrow"></use>
            </svg>
        </span>Back to List
    </a>
</div>

@using (Html.BeginForm())
{
    <div class="base">
        @if (!Html.ViewData.ModelState.IsValid)
        {
            <div class=" esg-alert esg-alert--fluid esg-alert--error" role="alert">
                <span class="esg-alert__icon-wrapper">
                    <span class="esg-alert__icon esg-icon__container" aria-hidden="True">
                        <svg class="esg-icon esg-icon--error-dark">
                            <use xlink:href="#icon-error"></use>
                        </svg>
                    </span>
                </span>

                <div class="esg-alert__message">
                    @Html.ValidationSummary(true, "", new { @class = "validation-summary-errors" })
                </div>
            </div><br />
        }
        <fieldset><br/>
            <div>
                <label class="esg-form__label">@Html.LabelFor(model => model.Keywords)</label>
            </div>
            <div class="esg-form__input-group">
                @Html.EditorFor(model => model.Keywords, new { htmlAttributes = new { @class = "esg-form__input" }, id = "Keywords" })
                @if (ViewData.ModelState["Keywords"] != null && ViewData.ModelState["Keywords"].Errors.Count > 0)
                {
                    <div class="esg-form__feedback-icon esg-icon__container">
                        <svg class="esg-icon esg-icon--error">
                            <use xlink:href="#icon-error"></use>
                        </svg>
                    </div>
                }
                @Html.ValidationMessageFor(model => model.Keywords, "", new { @class = "esg-form__feedback-text" })
            </div>
            <p>
                <input type="submit" value="Run" class="esg-button esg-button--primary" />
            </p>
        </fieldset>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

source/Ellucian.Colleague.Api/Ellucian.Colleague.Api/Areas/Student/Views/Test/CourseSearchParallel.cshtml
@model Ellucian.Colleague.Api.Areas.Student.Models.Tests.TestCourseSearch

@{
    ViewBag.Title = "CourseSearch";
}

@* Header/Title *@
<div class="esg-page-header">
    <h2 class="esg-page-header__title header-margin">Course Search</h2>
    <a href="@Url.Action("", "Test")" class="esg-page-header__subtitle esg-page-header__subtitle--backlink">
        <span class="esg-icon__container esg-page-header__icon" aria-hidden="true">
            <svg class="esg-icon esg-icon--left">
                <use xlink:href="#icon-arrow"></use>
            </svg>
        </span>Back to List
    </a>
</div>

@using (Html.BeginForm())
{
    <div class="base">
        @if (!Html.ViewData.ModelState.IsValid)
        {
            <div class=" esg-alert esg-alert--fluid esg-alert--error" role="alert">
                <span class="esg-alert__icon-wrapper">
                    <span class="esg-alert__icon esg-icon__container" aria-hidden="True">
                        <svg class="esg-icon esg-icon--error-dark">
                            <use xlink:href="#icon-error"></use>
                        </svg>
                    </span>
                </span>

                <div class="esg-alert__message">
                    @Html.ValidationSummary(true, "", new { @class = "validation-summary-errors" })
                </div>
            </div><br />
        }


        <fieldset>
            <br />
            <div>
                <label class="esg-form__label">@Html.LabelFor(model => model.Keywords)</label>
            </div>
            <div class="esg-form__input-group">
                @Html.EditorFor(model => model.Keywords, new { htmlAttributes = new { @class = "esg-form__input" }, id = "Keywords" })
                @if (ViewData.ModelState["Keywords"] != null && ViewData.ModelState["Keywords"].Errors.Count > 0)
                {
                    <div class="esg-form__feedback-icon esg-icon__container">
                        <svg class="esg-icon esg-icon--error">
                            <use xlink:href="#icon-error"></use>
                        </svg>
                    </div>
                }
                @Html.ValidationMessageFor(model => model.Keywords, "", new { @class = "esg-form__feedback-text" })
            </div>
            <p>
                <input type="submit" value="Run" class="esg-button esg-button--primary" />
            </p>
        </fieldset>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

source/Ellucian.Colleague.Api/Ellucian.Colleague.Api/Areas/Student/Views/Test/Courses.cshtml
@model Ellucian.Colleague.Api.Areas.Student.Models.Tests.TestCourses

@{
    ViewBag.Title = "Courses";
}

@* Header/Title *@
<div class="esg-page-header">
    <h2 class="esg-page-header__title header-margin">@ViewBag.Title</h2>
    <a href="@Url.Action("", "Test")" class="esg-page-header__subtitle esg-page-header__subtitle--backlink">
        <span class="esg-icon__container esg-page-header__icon" aria-hidden="true">
            <svg class="esg-icon esg-icon--left">
                <use xlink:href="#icon-arrow"></use>
            </svg>
        </span>Back to List
    </a>
</div>


@using (Html.BeginForm())
{
    <div class="base">
        @if (!Html.ViewData.ModelState.IsValid)
        {
            <div class=" esg-alert esg-alert--fluid esg-alert--error" role="alert">
                <span class="esg-alert__icon-wrapper">
                    <span class="esg-alert__icon esg-icon__container" aria-hidden="True">
                        <svg class="esg-icon esg-icon--error-dark">
                            <use xlink:href="#icon-error"></use>
                        </svg>
                    </span>
                </span>

                <div class="esg-alert__message">
                    @Html.ValidationSummary(true, "", new { @class = "validation-summary-errors" })
                </div>
            </div><br />
        }

        <fieldset>
            <legend>TestCourses</legend>
            <div>
                <label class="esg-form__label">@Html.LabelFor(model => model.CourseIds)</label>
            </div>
            <div class="esg-form__input-group">
                @Html.EditorFor(model => model.CourseIds, new { htmlAttributes = new { @class = "esg-form__input" }, id = "CourseIds" })
                @if (ViewData.ModelState["CourseIds"] != null && ViewData.ModelState["CourseIds"].Errors.Count > 0)
                {
                    <div class="esg-form__feedback-icon esg-icon__container">
                        <svg class="esg-icon esg-icon--error">
                            <use xlink:href="#icon-error"></use>
                        </svg>
                    </div>
                }
                @Html.ValidationMessageFor(model => model.CourseIds, "", new { @class = "esg-form__feedback-text" })
            </div>
            <p>
                <input type="submit" value="Run" class="esg-button esg-button--primary" />
            </p>
        </fieldset>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

source/Ellucian.Colleague.Api/Ellucian.Colleague.Api/Areas/Student/Views/Test/Credits.cshtml
@{
    ViewBag.Title = "Credits";
}

@* Header/Title *@
<div class="esg-page-header">
    <h2 class="esg-page-header__title header-margin">@ViewBag.Title</h2>
    <a href="@Url.Action("", "Test")" class="esg-page-header__subtitle esg-page-header__subtitle--backlink">
        <span class="esg-icon__container esg-page-header__icon" aria-hidden="true">
            <svg class="esg-icon esg-icon--left">
                <use xlink:href="#icon-arrow"></use>
            </svg>
        </span>Back to List
    </a>
</div>
<div class="base">
    <br />
    @using (Html.BeginForm("PostCredits", "Test"))
    {
        <input type="submit" value="Run" class="esg-button esg-button--primary" />
    }
    <br />
</div>

source/Ellucian.Colleague.Api/Ellucian.Colleague.Api/Areas/Student/Views/Test/Done.cshtml
@{
    ViewBag.Title = "Done";
    long elapsed = ViewBag.Elapsed;
    string exceptionMessage = ViewBag.ExceptionMessage;
    string log = ViewBag.Log;
    string result = ViewBag.Result;
}
@* Header/Title *@
<div class="esg-page-header">
    <h2 class="esg-page-header__title header-margin">Test Complete</h2>
    <a href="@Url.Action("", "Test")" class="esg-page-header__subtitle esg-page-header__subtitle--backlink">
        <span class="esg-icon__container esg-page-header__icon" aria-hidden="true">
            <svg class="esg-icon esg-icon--left">
                <use xlink:href="#icon-arrow"></use>
            </svg>
        </span>Back to List
    </a>
</div>
<div class="base"><br/>
    <p>
        Result: @result
    </p>
    <p>
        Time Elapsed: @elapsed ms
    </p>
</div>


@if (!string.IsNullOrEmpty(exceptionMessage))
{
    <div class="base">
        <h2>API Client Exception:</h2>
        <p>@exceptionMessage</p>
        <p></p>
        <h2>API Client Log:</h2>
        <p>@log</p>
    </div>
}

source/Ellucian.Colleague.Api/Ellucian.Colleague.Api/Areas/Student/Views/Test/Index.cshtml
@model Ellucian.Colleague.Api.Models.ApiTests

@{
    ViewBag.Title = "Colleague Web API Student Utilities";
    bool loggedIn = Ellucian.Web.Http.Configuration.LocalUserUtilities.IsLoggedIn(Request);
}

@* Header/Title *@
<div class="esg-page-header">
    <h2 class="esg-page-header__title header-margin">@ViewBag.Title</h2>
</div>

<div id="StudentUtilitiesTestbody">
    <section class="content-wrapper main-content clear-fix"><br/>
        <div class="base">
            <h3>Any Web API Host</h3>
            @if (!loggedIn)
            {
                <p>These tests require you to @Html.ActionLink("Login", "login", new { Area = "", Controller = "Admin" }) first.</p>
            }
            <br/>
            <p>These tests use the .NET API client against <strong>any</strong> Web API host.</p>
        </div>
        <table class="Utilities">
            <tr>
                <td>Academic history for current user</td>
                <td>GET &nbsp;&nbsp;&nbsp; @Html.ActionLink("students/{id}/academiccredits", "Credits", "Test", null, null)</td>
               
            </tr>
            <tr>
                <td>Search courses</td>
                <td>POST&nbsp;&nbsp;@Html.ActionLink("courses", "CourseSearch", "Test", null, null)</td>
            </tr>
            <tr>
                <td>Search courses (multiple at once)</td>
                <td>POST&nbsp;&nbsp;@Html.ActionLink("courses", "CourseSearchParallel", "Test", null, null)</td>
            </tr>
            <tr>
                <td>Get courses by ID(s)</td>
                <td>GET&nbsp;&nbsp;&nbsp; @Html.ActionLink("courses/{id1,id2,...}", "Courses", "Test", null, null)</td>
            </tr>
            <tr>
                <td>Get sections by ID(s)</td>
                <td>GET&nbsp;&nbsp;&nbsp; @Html.ActionLink("sections?sectionIds={id1,id2,...}", "Sections", "Test", null, null)</td>
            </tr>
            <tr>
                <td>Get sections by course ID(s)</td>
                <td >GET&nbsp;&nbsp;&nbsp; @Html.ActionLink("courses/sections?courseIds={id1,id2,...}", "SectionsForCourses", "Test", null, null)</td>
                
            </tr>
            <tr>
                <td>Get faculty by ID(s)</td>
                <td>POST&nbsp;&nbsp;@Html.ActionLink("faculty", "Faculty", "Test", null, null)</td>
            </tr>
        </table>
    </section>
</div>

source/Ellucian.Colleague.Api/Ellucian.Colleague.Api/Areas/Student/Views/Test/Subjects.cshtml
@{
    ViewBag.Title = "Subjects";
}

<h2>Subjects</h2>

@using (Html.BeginForm("PostSubjects", "Test"))
{
    <input type="submit" value="Run"/>
}


<div>
    @Html.ActionLink("Back to List", "Index")
</div>